# -*- coding: utf-8 -*-
"""digit_recogniser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JMaJVL9NhvZpqEtvfUlfmjYxY4NzaU0

# Digit Recognizer

- Load the libraries
- Load the Data
- Normalize the Data
- Build the architecture
- Split the data
"""

import torch
from matplotlib import pyplot as plt
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.nn import CrossEntropyLoss

device = "cuda" if torch.cuda.is_available() else "cpu"

from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

x_train_tensor = torch.tensor(x_train, dtype=torch.float32, device=device)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32, device=device)

y_train_tensor = torch.tensor(y_train, dtype=torch.int64, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.int64, device=device)

class CustomDataset(Dataset):
  def __init__(self, x_features, y_target):
    self.features = x_features
    self.target = y_target

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.target[index]

train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=False)

class DigitRecognizerNeuralNetwork(nn.Module):
  def __init__(self, ):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(in_features=784, out_features=512, bias=True),
        nn.ReLU(),
        nn.Linear(in_features=512, out_features=256, bias=True),
        nn.ReLU(),
        nn.Linear(in_features=256, out_features=128, bias=True),
        nn.ReLU(),
        nn.Linear(in_features=128, out_features=64, bias=True),
        nn.ReLU(),
        nn.Linear(in_features=64, out_features=32, bias=True),
        nn.ReLU(),
        nn.Linear(in_features=32, out_features=18, bias=True),
        nn.ReLU(),
        nn.Linear(in_features=18, out_features=10, bias=True)
    )

  def forward(self, x):
    x = x.flatten(start_dim=1)
    x_out = self.network(x)
    return x_out

model = DigitRecognizerNeuralNetwork().to(device=device)
criterion = CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-003)

from datetime import datetime

model.train()
now = datetime.now()
for epoch in range(25):
  train_loss = 0
  for x_batch, y_batch in train_dataloader:
    x_batch = x_batch.to(device)
    y_batch = y_batch.to(device)
    y_pred = model(x_batch)
    loss = criterion(y_pred, y_batch)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    train_loss += loss.item()

  print(f"Epoch {epoch + 1} | Loss {train_loss/len(train_dataloader)} | Time {datetime.now() - now}")

model.eval()
now = datetime.now()

correct = 0
total = 0

with torch.no_grad():
  test_loss = 0
  for x_batch, y_batch in test_dataloader:
    x_batch = x_batch.to(device)
    y_batch = y_batch.to(device)

    pred = model(x_batch)
    something, predicted = torch.max(pred, 1)
    #print(f"Something {something}, predicted {predicted}")

    correct += (predicted == y_batch).sum().item()
    total += y_batch.size(0)
print(f"Accuracy {100 * correct / total:.2f}")

correct = total = 0

with torch.no_grad():
  for x_batch, y_batch in train_dataloader:
    x_batch = x_batch.to(device)
    y_batch = y_batch.to(device)

    output = model(x_batch)

    _, predicted = torch.max(output, 1)

    correct += (predicted == y_batch).sum().item()
    total += y_batch.size(0)

print(f"Accuracy {100 * correct / total:.2f}")

